### ISSUE TITLE
Scrolling not smooth

### ISSUE THREAD

**Issue by tibotiber** [planecq/planecq.com#3]
For Romain on Chrominium. Could come from one of the libs.

**Comment by tibotiber** [comment]
Cleaned up assets in #5. This may have solved the issue.
@romainendelin can you test again? :)

**Comment by RomainEndelin** [comment]
The menu is perfect now, it's very fluid and beautiful !

The heading inside the jumbotron/caroussel is still a bit laggy on scroll. I suppose it's caused by a parallax effect (almost invisible because text and background have almost the same scrolling pace), so if you don't plan to make the parallax more visible, you may disable it for smoother scroll.

**Comment by tibotiber** [comment]
Indeed, wasn't even aware it was there. Removed it in 1787549. If it's better and you're happy, feel free to close the issue ;). Thanks a lot!

**Comment by RomainEndelin** [comment]
Yes, that's great :). But it seems like you're the only one who can close the issue.

**Comment by tibotiber** [comment]
Oh ok, thanks :)
